#!/usr/bin/env python

import sys


def bitsOfReg(reg, size):
    for i in range(size):
        if (reg >> i) & 1:
            print("bits"+str(i)+":" + "1")
        else:
            print("bits"+str(i)+":" + "0")


if __name__ == '__main__':
    reg = int(sys.argv[1], 16)
    bitsOfReg(reg, 32)
